version: '3.7'

services:
  svc-app:
    container_name: svc-app
    build: svc-app
    command:
      - /bin/bash
      - -c
      - |
        python3 -m pytest -s /svc-app/app -vv --cov-report=term-missing --cov="/svc-app/app"
        /bin/bash ./entrypoint-cmd.sh
    environment:
      APP_VERSION: ${APP_VERSION}
      HOST: ${HOST}                         # 0.0.0.0
      PORT: ${PORT}                         # 8002
      APP_HOSTNAME: "localhost:${PORT}"
      APP_ENV: ${APP_ENV}                   # One of: local, testing, develop, staging, master
      JIRA_SERVER_URL: ${JIRA_SERVER_URL}   # https://YOUR_JIRA_SERVER_URL.atlassian.net
      JIRA_LOGIN: ${JIRA_LOGIN}             # YOUR_EMAIL_AS_JIRA_LOGIN@gmail.com
      JIRA_API_TOKEN: ${JIRA_API_TOKEN}     # # see: [https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/]
      LOG_LEVEL: ${LOG_LEVEL}               # One of: debug, info, warning, error, critical
      MONGO_PORT: ${MONGO_PORT}
      MONGO_SERVER: ${MONGO_SERVER}
      MONGO_DSN: "mongodb://${MONGO_INITDB_USER}:${MONGO_INITDB_PASSWORD}@${MONGO_SERVER}:${MONGO_PORT}/${MONGO_INITDB_DATABASE}"
    env_file:
      ./.env
    ports:
      - "8002:${PORT}"
    volumes:
      - ./svc-app:/svc-app                  # hot reload on files modification
    extra_hosts:
      - "docker_host: ${IP_ADDRESS}"
    depends_on:
      - ${MONGO_SERVER}
    networks:
      - net-internal

  svc-mongo:
    container_name: ${MONGO_SERVER} # do not change. Name is hardcoded in entrypoint.sh and ME_CONFIG_MONGODB_URL
    build: svc-mongo
    command: mongod --auth --quiet  --logpath ${MONGO_LOG_DIR}
    restart: always
    environment:
      MONGO_DATA_DIR: "/data/db"
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USER: ${MONGO_INITDB_USER}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:${MONGO_PORT}"
    volumes:
      - ./data-mongo:/data/db
      - ./svc-mongo/initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - net-internal

  mongo-express:
    container_name: mongo-express
    build: svc-mongo-express
    restart: always
    ports:
      - "8081:${MONGO_EXPRESS_PORT}"
    environment:
      MONGO_SERVER: ${MONGO_SERVER}
      MONGO_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${ME_CONFIG_MONGODB_ENABLE_ADMIN}
      ME_CONFIG_OPTIONS_EDITORTHEME: ${ME_CONFIG_OPTIONS_EDITORTHEME}
      ME_CONFIG_MONGODB_SERVER_WAIT_MAX_TRIES: ${ME_CONFIG_MONGODB_SERVER_WAIT_MAX_TRIES}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_SERVER}
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_SERVER}:${MONGO_PORT}/?authSource=admin"
    links:
      - ${MONGO_SERVER}
    depends_on:
      - ${MONGO_SERVER}
    networks:
      - net-internal

networks:
  net-internal: { }




